FROM nginx:alpine

# Instalar OpenSSL
RUN apk add --no-cache openssl

# Generar certificado autofirmado para desarrollo local
RUN mkdir -p /etc/nginx/ssl && \
    openssl req -x509 -nodes -days 365 -newkey rsa:2048 \
    -keyout /etc/nginx/ssl/nginx.key \
    -out /etc/nginx/ssl/nginx.crt \
    -subj "/C=ES/ST=Spain/L=Madrid/O=ProyectoFinanzas/OU=Dev/CN=localhost"

EXPOSE 80 443
